version: '3.8'

services:
  mysql:
    image: mysql:8.0.43-debian
    environment:
      MYSQL_DATABASE: linkedin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3309:3306'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025' # web UI for viewing emails